### ISSUE TITLE
Errors from ampersands running the script

### ISSUE THREAD

**Issue by Fossie1973** [arcanecode/PowerShell#1]
Thanks for doing this project! Very usable as I'm in the same situation. I do, however, have problems running the script, apparently PowerShell does not enjoy the use of ampersands in the code. Here's what I get when running it:

Best regards,

Steinar

PS C:\WINDOWS\system32> C:\IPAddressMailer\IPAddressMailer.ps1
At C:\IPAddressMailer\IPAddressMailer.ps1:143 char:19
+               Sign&nbsp;up
+                   ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass 
it as part of a string.
At C:\IPAddressMailer\IPAddressMailer.ps1:170 char:190
+ ... ata-ga-click="(Logged out) Header, go to Features">Features <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\IPAddressMailer\IPAddressMailer.ps1:170 char:261
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass 
it as part of a string.
At C:\IPAddressMailer\IPAddressMailer.ps1:184 char:255
+ ... ogged out) Header, go to Customer stories">Customer stories <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\IPAddressMailer\IPAddressMailer.ps1:184 char:326
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass 
it as part of a string.
At C:\IPAddressMailer\IPAddressMailer.ps1:185 char:231
+ ... ata-ga-click="(Logged out) Header, go to Security">Security <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\IPAddressMailer\IPAddressMailer.ps1:185 char:302
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass 
it as part of a string.
At C:\IPAddressMailer\IPAddressMailer.ps1:205 char:222
+ ... a-click="(Logged out) Header, go to Explore">Explore GitHub <span cla ...
+                                                                 ~
The '<' operator is reserved for future use.
At C:\IPAddressMailer\IPAddressMailer.ps1:205 char:293
+ ... ="Bump-link-symbol float-right text-normal text-gray-light">&rarr;</s ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass 
it as part of a string.
At C:\IPAddressMailer\IPAddressMailer.ps1:208 char:107
+ ...  text-normal text-mono f5 mb-2 border-lg-top pt-lg-3">Learn &amp; con ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass 
it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by arcanecode** [comment]
Have you made changes to the script I created? I’m looking in my original script and I have no references to any of the text strings you are getting errors on.

Thanks,

    Robert

Robert C. Cain
Arcane Training and Consulting, LLC
Author, Pluralsight<http://www.pluralsight.com/author/robert-cain>  | Author, Red Gate<http://arcanecode.red/> | Book Author, PACKT<https://www.packtpub.com/big-data-and-business-intelligence/sql-server-2016-reporting-services-cookbook>
arcanecode.me<http://arcanecode.me/> | @ArcaneTC<https://twitter.com/ArcaneTC> | LinkedIN<https://www.linkedin.com/in/arcanecode/> | Facebook<https://www.facebook.com/arcanetc>

**Comment by Fossie1973** [comment]
The only changes I made was updating the email addresses, password and setting the mail-every-time variable to true. I'm not by my computer that ran the script right now, but I did check on some of the errors yesterday. For instance, the error on line 143 did not appear to be part of a string:

`Sign&nbsp;up`

It is part of the following block of code:

`        <div class="d-flex flex-items-center">

            <a href="/join?source=header-repo"

              class="d-inline-block d-lg-none f5 text-white no-underline border border-gray-dark rounded-2 px-2 py-1 mr-3 mr-sm-5"

              data-hydro-click="{&quot;event_type&quot;:&quot;authentication.click&quot;,&quot;payload&quot;:{&quot;location_in_page&quot;:&quot;site header&quot;,&quot;repository_id&quot;:null,&quot;auth_type&quot;:&quot;SIGN_UP&quot;,&quot;client_id&quot;:&quot;493009869.1562053357&quot;,&quot;originating_request_id&quot;:&quot;E92A:10EA9:417EF:61C7D:5D1B8319&quot;,&quot;originating_url&quot;:&quot;https://github.com/arcanecode/PowerShell/blob/master/IPAddressMailer/IPAddressMailer.ps1&quot;,&quot;referrer&quot;:&quot;https://github.com/arcanecode/PowerShell/tree/master/IPAddressMailer&quot;,&quot;user_id&quot;:null}}" data-hydro-click-hmac="51a4bc6c48ea8f4a42864aff1fc44112bcd5a9b03d4bfa4a3f71251936753a8e"

              data-ga-click="(Logged out) Header, clicked Sign up, text:sign-up">

              Sign&nbsp;up
            </a>`

I'm not very experienced with PowerShell scripts, so I might be way off here, but then again, a clean copy-paste is usually within my capabilities :)

Best regards

**Comment by arcanecode** [comment]
I see what happened. Somehow when you copied the code you also managed to snag all of GitHub’s HTML they use to display a page. That extra stuff is all HTML from github, not part of my code.

If you are on github, right above the code listing there is a button that says “Raw”. Click it and it will display just my PowerShell script, and not any of the HTML github uses to show the page. The raw page can then be easily copy / pasted, or use “File | Save As” in the browser to save it as a PS1 file.

Thanks,

    Robert

Robert C. Cain
Arcane Training and Consulting, LLC
Author, Pluralsight<http://www.pluralsight.com/author/robert-cain>  | Author, Red Gate<http://arcanecode.red/> | Book Author, PACKT<https://www.packtpub.com/big-data-and-business-intelligence/sql-server-2016-reporting-services-cookbook>
arcanecode.me<http://arcanecode.me/> | @ArcaneTC<https://twitter.com/ArcaneTC> | LinkedIN<https://www.linkedin.com/in/arcanecode/> | Facebook<https://www.facebook.com/arcanetc>

**Comment by Fossie1973** [comment]
Thanks for checking up on this.

I didn't copy anything from my browser, I downloaded the files and copied from there, so I guess the files could use an update.

You showed me the way though, so I'll be good to go again once I get to my remote computer on Monday. The code looks so much more readable and clean now, with your standard of commenting it'll be easy to follow what you're doing.

Great job man, and thanks again!

**Comment by Fossie1973** [comment]
Thinking of it, perhaps the problem is with how GitHub serves the files rather than the files themselves? Maybe something they could check up on if that is the case.

**Comment by yxchiwork** [comment]
> Thinking of it, perhaps the problem is with how GitHub serves the files rather than the files themselves? Maybe something they could check up on if that is the case.

Then probably close this issue since it's not a valid issue?

**Comment by michaelong8** [comment]
This is related to something similar i faced when i tried to update azure modules using the github provided ps1 file.  Clicking Raw finally got it working.

Glad i glanced on this thread.

**Comment by 2billcom** [comment]
Got the same issue when running the following code to connect and populate my mongodb in connection with Express

 node populatedb mongodb+srv://billa:2samjella123@cluster-00.v1kq5.mongodb.net/dbnodejs?retryWrites=true&w=majority
